import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'category',
      label: 'Atlas Protocol',
      items: [
        'protocol/architecture',
        'protocol/x-storage',
        'protocol/x-filetree',
      ],
    },
    {
      type: 'category',
      label: 'atlas.js',
      items: [
        'atlas-js/intro',
        'atlas-js/getting-started',
        'atlas-js/atlas-client',
        'atlas-js/storage-handler',
      ],
    }
  ],

  api: [
    {
      type: 'autogenerated',
      dirName: 'api',
    },
  ],
};

export default sidebars;
